PUZZLES = [
    # Thing
    ("BIRTHDAY CAKE", "Thing"),
    ("SWIMMING POOL", "Thing"),
    ("GARDEN HOSE", "Thing"),
    ("ALARM CLOCK", "Thing"),
    ("CEILING FAN", "Thing"),
    ("COFFEE MUG", "Thing"),
    ("BASKETBALL HOOP", "Thing"),
    ("FIRE EXTINGUISHER", "Thing"),
    ("ROCKING CHAIR", "Thing"),
    ("SNOW GLOBE", "Thing"),
    ("TELESCOPE", "Thing"),
    ("PIGGY BANK", "Thing"),
    ("DIVING BOARD", "Thing"),
    ("WELCOME MAT", "Thing"),
    ("MAGNIFYING GLASS", "Thing"),

    # Place
    ("NIAGARA FALLS", "Place"),
    ("TIMES SQUARE", "Place"),
    ("GRAND CANYON", "Place"),
    ("EIFFEL TOWER", "Place"),
    ("CENTRAL PARK", "Place"),
    ("GOLDEN GATE BRIDGE", "Place"),
    ("MOUNT RUSHMORE", "Place"),
    ("STATUE OF LIBERTY", "Place"),
    ("EMPIRE STATE BUILDING", "Place"),
    ("YELLOWSTONE NATIONAL PARK", "Place"),
    ("VENICE BEACH", "Place"),
    ("BOURBON STREET", "Place"),
    ("BUCKINGHAM PALACE", "Place"),
    ("GREAT BARRIER REEF", "Place"),
    ("SAHARA DESERT", "Place"),

    # Person
    ("ALBERT EINSTEIN", "Person"),
    ("MARIE CURIE", "Person"),
    ("ABRAHAM LINCOLN", "Person"),
    ("CLEOPATRA", "Person"),
    ("LEONARDO DA VINCI", "Person"),
    ("NEIL ARMSTRONG", "Person"),
    ("WILLIAM SHAKESPEARE", "Person"),
    ("MARTIN LUTHER KING", "Person"),
    ("AMELIA EARHART", "Person"),
    ("BENJAMIN FRANKLIN", "Person"),
    ("ROSA PARKS", "Person"),
    ("CHARLES DARWIN", "Person"),
    ("FRIDA KAHLO", "Person"),
    ("NIKOLA TESLA", "Person"),
    ("HARRIET TUBMAN", "Person"),

    # Phrase
    ("ACTIONS SPEAK LOUDER THAN WORDS", "Phrase"),
    ("EVERY CLOUD HAS A SILVER LINING", "Phrase"),
    ("THE EARLY BIRD CATCHES THE WORM", "Phrase"),
    ("BETTER LATE THAN NEVER", "Phrase"),
    ("BITE THE BULLET", "Phrase"),
    ("HIT THE NAIL ON THE HEAD", "Phrase"),
    ("BREAK A LEG", "Phrase"),
    ("SPILL THE BEANS", "Phrase"),
    ("UNDER THE WEATHER", "Phrase"),
    ("ONCE IN A BLUE MOON", "Phrase"),
    ("COST AN ARM AND A LEG", "Phrase"),
    ("LET THE CAT OUT OF THE BAG", "Phrase"),
    ("BURNING THE MIDNIGHT OIL", "Phrase"),
    ("JUMP ON THE BANDWAGON", "Phrase"),
    ("THE BALL IS IN YOUR COURT", "Phrase"),

    # Before & After
    ("PEANUT BUTTER CUP CAKE", "Before & After"),
    ("HOT DOG HOUSE MUSIC", "Before & After"),
    ("ROCK BAND WAGON", "Before & After"),
    ("GOLD FISH TANK TOP", "Before & After"),
    ("BLACK BIRD HOUSE", "Before & After"),
    ("SNOW BALL PARK", "Before & After"),
    ("SUN FLOWER POWER", "Before & After"),
    ("FIRE TRUCK STOP", "Before & After"),
    ("RAIN BOW TIE", "Before & After"),
    ("MOON LIGHT HOUSE", "Before & After"),

    # Food & Drink
    ("MACARONI AND CHEESE", "Food & Drink"),
    ("CHICKEN PARMESAN", "Food & Drink"),
    ("STRAWBERRY SHORTCAKE", "Food & Drink"),
    ("FRENCH ONION SOUP", "Food & Drink"),
    ("EGGS BENEDICT", "Food & Drink"),
    ("BANANA SPLIT", "Food & Drink"),
    ("GRILLED CHEESE SANDWICH", "Food & Drink"),
    ("CHOCOLATE LAVA CAKE", "Food & Drink"),
    ("CAESAR SALAD", "Food & Drink"),
    ("PEANUT BUTTER AND JELLY", "Food & Drink"),

    # Event
    ("SUPER BOWL SUNDAY", "Event"),
    ("NEW YEARS EVE PARTY", "Event"),
    ("FOURTH OF JULY FIREWORKS", "Event"),
    ("THANKSGIVING DINNER", "Event"),
    ("HALLOWEEN COSTUME PARTY", "Event"),
    ("MARDI GRAS PARADE", "Event"),
    ("ACADEMY AWARDS CEREMONY", "Event"),
    ("WORLD CUP FINAL", "Event"),
    ("SOLAR ECLIPSE", "Event"),
    ("OLYMPIC OPENING CEREMONY", "Event"),

    # Around the House
    ("KITCHEN SINK", "Around the House"),
    ("LIVING ROOM COUCH", "Around the House"),
    ("MASTER BEDROOM", "Around the House"),
    ("WALK IN CLOSET", "Around the House"),
    ("BATHROOM MIRROR", "Around the House"),
    ("FRONT PORCH SWING", "Around the House"),
    ("GARAGE DOOR OPENER", "Around the House"),
    ("BASEMENT STAIRS", "Around the House"),
    ("BACKYARD PATIO", "Around the House"),
    ("DINING ROOM TABLE", "Around the House"),

    # What Are You Doing?
    ("TAKING A BUBBLE BATH", "What Are You Doing?"),
    ("WALKING THE DOG", "What Are You Doing?"),
    ("MAKING BREAKFAST", "What Are You Doing?"),
    ("WATCHING THE SUNSET", "What Are You Doing?"),
    ("READING A GOOD BOOK", "What Are You Doing?"),
    ("PLAYING VIDEO GAMES", "What Are You Doing?"),
    ("BAKING CHOCOLATE CHIP COOKIES", "What Are You Doing?"),
    ("TAKING OUT THE TRASH", "What Are You Doing?"),
    ("MOWING THE LAWN", "What Are You Doing?"),
    ("PAINTING THE BEDROOM", "What Are You Doing?"),
    ("LEARNING TO PLAY GUITAR", "What Are You Doing?"),
    ("RUNNING A MARATHON", "What Are You Doing?"),
    ("FEEDING THE DUCKS", "What Are You Doing?"),
    ("BUILDING A SANDCASTLE", "What Are You Doing?"),
    ("CLEANING THE GARAGE", "What Are You Doing?"),

]